### ISSUE TITLE
[bug]: Uninstall/reinstall requires reconfiguring dependents

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1026]
Steps to reproduce:

1. Install LND and RTL
2. Configure and run both services
3. Stop LND
4. Uninstall LND (optionally back it up somewhere)
5. Reinstall LND
6. Configure LND
7. Visit RTL in the browser
8. RTL refuses to connect to LND

If I then stop RTL and reconfigure it, it starts working again.

**Comment by ProofOfKeags** [comment]
The fix for this is twofold:

1. If a pointer is pointing to a resource that no longer exists, dereferencing it should yield the `null` value. This is supposedly already true for `ConfigPointer`s but needs to be true for pointers of other types.
2. If a resource is restored, the pointers that have references to it should have the values updated to reflect the new values.

CC @dr-bonez

**Comment by dr-bonez** [comment]
`/current-dependents/<id>/pointers` is an array of all pointers that need to be updated in dependents.

**Comment by ProofOfKeags** [comment]
Before someone reopens this aggressively saying that dependent services still need to be restarted. This is a broader issue with how to handle the dynamism of pointer volumes. Further work on this is captured in #1073. For now, we no longer require reconfiguring the dependent to ingest those changes, but we do require restarting it if the service depends on pointer volume data for essential function. In the mean time, if you depend on critical data in a pointer volume and it isn't available on service startup, the current recommendation is to exit with a ZERO exit code. This WILL put your service into a crash loop while it waits for those volumes to be available. This is palatable assuming that this broken state is transient while you reinstall/reconfigure/restart the dependency.
