### ISSUE TITLE
[bug]: LND and spark issue crash notifications during system backup

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1038]
Steps to reproduce:
1. Install these services:
<img width="1152" alt="Screen Shot 2022-01-06 at 3 44 22 PM" src="https://user-images.githubusercontent.com/7445670/148456383-2178f242-9c8a-4942-aafc-05f37b88a0be.png">
2. Do a system backup
3. Backup hangs on bitcoind:
<img width="1162" alt="Screen Shot 2022-01-06 at 3 45 09 PM" src="https://user-images.githubusercontent.com/7445670/148456444-65c66158-65e3-4f5e-8fd2-d2ff08fd2516.png">
4. Dependent services start issuing crash notifications every 15 minutes:
<img width="1167" alt="Screen Shot 2022-01-06 at 3 42 32 PM" src="https://user-images.githubusercontent.com/7445670/148456271-753c2a53-d62e-4018-9d89-38ae21d029af.png">

**Comment by dr-bonez** [comment]
This happens because bitcoin core is paused during backup, and lnd relies on it being always up. Not sure how to address this rn. Since we've had so many issues with lnd and c-lightning crashing, I'm inclined to say we should change the behavior so that they don't crash during breif interruptions of rpc access to bitcoind and instead have them fail a health check. This will require a more advanced init script for these packages.

@chrisguida

**Comment by ProofOfKeags** [comment]
Proposed Solution: Freeze dependents when you freeze the service.
