### ISSUE TITLE
Modal size

### ISSUE THREAD

**Issue by elvece** [Start9Labs/embassy-os#1079]
Could the confirmation modals for actions be larger? There can sometimes be a decent amount of text in these, and it would be more readable if wider horizontally. 

<img width="1680" alt="Screen Shot 2022-01-14 at 6 26 02 PM" src="https://user-images.githubusercontent.com/12953208/149603640-2cdf582f-b170-46db-950d-8df7102bea91.png">

**Comment by DrewAns** [comment]
@elvece they could be larger.  Are there messages that are too short for a larger modal?  Would that also look awkward?

**Comment by ProofOfKeags** [comment]
I think no matter what if we wish to make these bigger, they need to be variable. The choice for the current size was likely made due to the expectation that they would be used on mobile. As a result, if you fix the width at something wider than a standard mobile screen width it will essentially break the mobile experience. As a result if we go wider with them it will have to be adaptive to screen width. I don't think that would be harder than the rest of the responsive design elements we have so this should be very doable with the same tools. However, I'm not a CSS expert so I could be misjudging the situation.
