### ISSUE TITLE
[feat]: [UI]: button to export logs to a text file and download

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#1341]
This would be amazing for debugging user issues. Can probably be implemented alongside https://github.com/Start9Labs/embassy-os/issues/732

**Comment by dr-bonez** [comment]
@elvece let me know what apis you need to enable this if existing ones aren't sufficient.

**Comment by spencerflagg** [comment]
Would be neat to give the option to write logs to disk constantly, for debugging purposes.
- user points the logger to a LAN shared folder
- user sets a timeframe to keep logs
- badge in header of the desktop UI reminds the user that saved logging is still enabled

**Comment by chrisguida** [comment]
Currently the logs are stored in journald, which does exactly what you say, only issue is they're only accessible via the command line.

But that's an interesting idea to mirror them via cifs

**Comment by spencerflagg** [comment]
Ahh - good to remember, thanks.

**Comment by elvece** [comment]
As suggested [here](https://github.com/Start9Labs/embassy-os/issues/1416), also make current page of logs easily copy/pasteable in all environments (mobile + desktop).

**Comment by elvece** [comment]
After discussion with @MattDHill, we decided that the best solution is to simply implement [copy/paste functionality](https://github.com/Start9Labs/embassy-os/issues/1416) (with simple backtick formatting so that it's very straightforward for users to share logs. Having to navigate to the downloaded file, especially from within a mobile device, is more cumbersome than copy/pasting to a support channel. The copy functionality copies all logs currently loaded into view, so no need to scroll back and copy again. This resolves the intended need as far as I'm concerned.

**Comment by chrisguida** [comment]
Not sure I like this solution. First, this probably doesn't capture all logs in journald, since it only captures "all logs currently loaded into view", which means that old logs beyond the UI buffer will not be copied.

Second, when pasting into a support channel, depending on the size of the logfile being pasted, a giant wall of text can get pretty obnoxious. When I created this ticket I was picturing an export of everything from `journald`.

**Comment by MattDHill** [comment]
Hmm will discuss with @elvece today.

**Comment by gStart9** [comment]
Another vote for this one.  Have a windows user that would have greatly benefited from this today.  He scrolled up 63 pages to copy it page by page.  I'm not even 100% sure they got to the event they needed (the all-services-go-back-to-needsconfig bug) in 63 pages.

**Comment by MattDHill** [comment]
We're going to do the file download, but not in 0.3.1 since there is backend work required
