### ISSUE TITLE
[feat]: "New" badge for new config options upon service update

### ISSUE THREAD

**Issue by kn0wmad** [Start9Labs/embassy-os#1528]
### Prerequisites

- [X] I have searched for [existing issues](https://github.com/start9labs/embassy-os/issues) that already suggest this feature, without success.

### Describe the Feature Request

When a service update is completed, if a feature has been added, such as a new config option, it would quickly draw the user's attention to the new config option so they may decide if or what they might like to do about it

### Describe the Use Case

Better UX

### Anything else?

Nice to have: Tooltip option on the badge, such that if a config is edited on behalf of the user, the change can be explained.  This gives them the information to keep or edit that change

**Comment by chrisguida** [comment]
This feature used to exist on 0.2 but I haven't seen it on 0.3

**Comment by chrisguida** [comment]
I'm going to hold CLN with CLBOSS until this is fixed. The user needs to be able to see that CLBOSS is now and option, and they need to confirm that they want it active. Otherwise their node will just start doing smart things and they won't know why.

<img width="1436" alt="Screen Shot 2022-06-14 at 1 31 47 PM" src="https://user-images.githubusercontent.com/7445670/173663331-b29adb33-c6bf-4494-93f9-2875b0b88aa9.png">

^ This is what the config modal looks like after upgrading from 0.11.1 -> 0.11.1.1. No indication of new config options.

**Comment by elvece** [comment]
Fixed by: https://github.com/Start9Labs/embassy-os/pull/1537/commits/737c17671ccaec30feb8942491130f091ed77ed3
