### ISSUE TITLE
Undo autoconfig on dependent uninstall.

### ISSUE THREAD

**Issue by afg419** [Start9Labs/embassy-os#158]
As a user with service A depending on B such that A has altered B's config (or A has imposed restrictions on B's config which are now satisfied), uninstalling wizard for A will present a checkbox option to undo the alterations to B's config.

**Comment by chrisguida** [comment]
These seems like a useful feature, what was the reason for closing?

**Comment by MattDHill** [comment]
I think there's a debate to be had whether or not it's useful.

If it is useful, it seems marginally so and probably isn't worth the debate or effort to implement. I could also see this cause problems or confusion.

Why do you think it is good?

**Comment by chrisguida** [comment]
Because when you uninstall a service, you expect it to remove all traces

**Comment by MattDHill** [comment]
So switch Bitcoin back to pruned?

**Comment by MattDHill** [comment]
My point is that the benefits of this feature are tiny but the complexity, effort, and risks are higher.

**Comment by chrisguida** [comment]
It's just not good software practice to leave dangling garbage around that isn't being used. There are probably too few services available currently to fully see the effects of this behavior. But sooner or later, once there are dozens of services on the marketplace and we have tens of thousands of users, people will start to notice this and it won't be fun.

**Comment by MattDHill** [comment]
That is actually my preferred way of iterating. If it begins to be a problem, then we will begin to solve it. It's not a problem at the moment, and I'm not at all convinced it ever will be. Auto configuring a dependency makes sense because most auto configurations are additive, meaning (1) they are unlikely to break another service and (2) they are likely harmless to leave in place.

Auto unconfiguring a dependency, on the other hand, is far more complicated, since it carries a significantly higher probability that it will inadvertantly break another service.

I would go so far as to say dependency auto config might even be an anti feature, something that could cause more harm than good.

**Comment by chrisguida** [comment]
I'm just saying, it's a problem that needs to be solved one way or another eventually. It's essentially tech debt. There are bad ways to solve it and good ways. We should research and find the good ways. We should not implement the bad ways.
