### ISSUE TITLE
UI: On update, we see "update anyway" disabled while it's checking for dependencies, which is weird, if the check comes back empty

### ISSUE THREAD

**Issue by afg419** [Start9Labs/embassy-os#172]

**Comment by adamgoth** [comment]
I looked into this a little bit as it seemed like a good opportunity for me to learn more about how components are constructed and pieced together in Angular/Ionic.

I agree with @afg419 that it is strange to see “Update Anyways” text on a disabled button before knowing if the “Update Anyways” text is relevant or not.

It looks like while the `cancelButton` can have an `afterLoading` or `whileLoading` value specified, the `nextButton` is typed to only have one string value, independent of loading state.

I see at least two possible solutions. The quickest solution would be to add a check to the `ngIf` for the `nextButton` that would hide the button entirely if something is loading (`*ngIf="!($anythingLoading$ | async) && currentSlideDef.nextButton as nextButton" `).

A possible problem is this is it would hide all `nextButton`’s on all slides if something is loading. I don’t have enough experience with the install wizard to know if that would be an issue or a desired outcome. We do use that same loading logic to disable the `nextButton` though so it wouldn’t be hiding anything that a user could actually click anyways.

The other solution I see would be to update all `nextButton`’s to be similar to `cancelButton`’s and have `whileLoading` and `afterLoading` values instead of just the one string value. This seems like it would be more involved of a solution as I see 11 additional `nextButton`’s used throughout `prebaked-wizards.ts` that would need to be updated aside from the “Update Anyways” button.

@afg419 @MattDHill  Hopefully I interpreted this correctly and that all makes sense. Happy to work on a solution for this depending on what approach you think is best.

**Comment by afg419** [comment]
Heyo this `*ngIf="!($anythingLoading$ | async) && currentSlideDef.nextButton as nextButton"` is exactly the approach I took in 0.2.9. I believe this ticket is in the user acceptance testing slot of the board. In playing around with it, hiding the buttons altogether seems aok. 

Now I should say, the wizard stuff is not 'angular' in any traditional sense, it's all my hackery and it's a mess complete with dead code hanging around, deep ion-slide bugs and hacks on top of them, and major issues with extensibility (e.g. say I want the data loaded in one slide to be used in a subsequent slide, or conditionally render a slide based on that date... would be difficult.) The whole thing needs a good rearchitecting.

**Comment by adamgoth** [comment]
Oh nice, happy to hear that particular approach did the trick. I also appreciate the background context on the wizard stuff. 

When you say “the board”, is that an internal board or something public that I’d be able to view somewhere?
