### ISSUE TITLE
Support building from the release source code tarball

### ISSUE THREAD

**Issue by chrisguida** [Start9Labs/embassy-os#207]
Currently all 3 components of embassy-os rely on access to the git history in order to build. It's been suggested to disable a "git" build feature when in the absence of a .git directory to enable builds from the pure source (eg https://github.com/Start9Labs/embassy-os/archive/v0.2.8.tar.gz).

**Comment by ProofOfKeags** [comment]
OK. In order to do this we'd probably need to make it a build step and set a build flag for the various subcomponents depending on whether that information is available. I would implement it in the agent but it is going away. My guess is that for appmgr this would be dealt with as a feature flag that is disabled if the git directory isn't present.
