### ISSUE TITLE
Don't allow service to start before meeting dependencies.

### ISSUE THREAD

**Issue by k0gen** [Start9Labs/embassy-os#825]
I have just installed LND. With Bitcoin service still doing sync and no Bitcoin Proxy installed.
At this stage:
I was able to configure LND - That's OK
And I was able to start the LND service - That should not be allowed.

![Screenshot from 2021-11-20 11-39-13](https://user-images.githubusercontent.com/3606313/142723351-2b50ad43-0cf2-420d-ac8a-027061c41246.png)

The solution would be to not allow user to start service if not all dependencies are met and if for some reason user want's to run that service add "force run" option (if necessary)

Worth considering:
Inform user that some services are still doing something like bitcoin has not finished syncing the blockchain and in case of LND some functions will be limited or don't work at all.

**Comment by ProofOfKeags** [comment]
This is an intentional design choice in 0.3.0.

The only scenario where we prohibit an app from starting on the grounds that its dependencies aren't met is if there is a "critical" dependency on the application. This is because if you configure LND against an *external* `bitcoind`, you want to be able to start `lnd` without `bitcoind` being installed.

That said, something about the behavior you observed was unintuitive to you, and that itself is an issue. Can you elaborate on your thought process that led you to believe this was an issue that needed to be fixed?

**Comment by k0gen** [comment]
The intentional design choice is good it just has to be extended a bit.
The ability to start service or not allow starting at all should be determined at the configuration stage.

The default (easy) auto config expects working Bitcoin and Bitcoin Proxy services if any or both are not operational starting the service should not be allowed.

**Comment by ProofOfKeags** [comment]
@dr-bonez I think it may be sensible to make a change here such that if a service holds onto active package pointers that it should inherit the requirement that those services be in the started state.

**Comment by dr-bonez** [comment]
>This is because if you configure LND against an external bitcoind, you want to be able to start lnd without bitcoind being installed.

This is not why, actually. The config pointer system already handles this and if you are using an external bitcoind, there will not be any dependency error. 

We allow you to start the service because there is nothing wrong with doing so, and may be a more convenient workflow. We still inform you that something is wrong with the service, similar to if you were running the service and it was failing a health check. Preventing a service from running while having an issue with a dependency can have all sorts of undesirable cascading effects. 

The fact that this was not intuitive to you _is_ still an issue, however. What this tells me is that the messaging around dependency errors is insufficient. Perhaps the start button should be yellow, and present a warning dialog in this state. Perhaps the `running` status should be replaced with a `running with errors` status when dependency errors are present or health checks are falling. 

Please weigh in @MattDHill

**Comment by MattDHill** [comment]
For 0.3.0, I will add a warning alert when attempting to start a service with a dependency error.

For a later release, @dr-bonez  and I agree it would be nice to have a "severity" attribute on health checks and dependencies that the UI can use to message things properly.

**Comment by ProofOfKeags** [comment]
Was a corresponding ticket cut describing the future improvements needed? I don't want to lose the pointer to this.

**Comment by MattDHill** [comment]
No, I described the fix in my precious comment and then merged the fix to 0.3.0 and closed the ticket.

**Comment by ProofOfKeags** [comment]
> For a later release, @dr-bonez and I agree it would be nice to have a "severity" attribute on health checks and dependencies that the UI can use to message things properly.

Do you wish to track this part though?

**Comment by MattDHill** [comment]
Ah, I understand now. I read future as feature. Yes, I have a note to cut a ticket for that, just didn't get around to it yet.
